package interfaz_grafica;

import javax.swing.JOptionPane;
// import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.imageio.ImageIO;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import clases.Cliente;
import operaciones_DAO.ClienteDAO;
import operaciones_DAO.ConexionDAO;

import javax.swing.JTextField;

// import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
// import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author Javier Rodríguez Montero
 */
public class InterfazFormulario extends javax.swing.JFrame {

	/*
	 * public class VentanaImagen extends JPanel {
	 * 
	 *//**
		* 
		*/
	/*
	
	*//**
		 * Create the panel.
		 *//*
			 * 
			 * public VentanaImagen() { this.setSize(570, 230);
			 * 
			 * String rutaImg = "." + File.separator + "img" + File.separator +
			 * "Bienvenido.png"; ImageIcon imageIcon = new
			 * ImageIcon(this.getClass().getResource(rutaImg)); JLabel label = new
			 * JLabel(imageIcon); add(label);
			 * 
			 * }
			 * 
			 * public void paint(Graphics grafico) { Dimension height = getSize(); ImageIcon
			 * Img = new ImageIcon( getClass().getResource("." + File.separator + "img" +
			 * File.separator + "Bienvenido.png")); grafico.drawImage(Img.getImage(), 0, 0,
			 * height.width, height.height, null); setOpaque(false);
			 * super.paintComponent(grafico); } }
			 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form InterfazFormulario
	 */
	public InterfazFormulario() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// @SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanelSignIn = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabelSignIn = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jTextFieldContrasena = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jTextFieldUsuario = new javax.swing.JTextField();
		jButtonSignIn = new javax.swing.JButton();
		jPanelSignUp = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		jLabelSignUp = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jTextFieldNombreContacto = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextFieldNombreCliente = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jTextFieldFax = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jTextFieldTelefonoContacto = new javax.swing.JTextField();
		jRadioButtonCalle = new javax.swing.JRadioButton();
		jRadioButtonAvenida = new javax.swing.JRadioButton();
		jRadioButtonBoulevard = new javax.swing.JRadioButton();
		jComboBox1 = new javax.swing.JComboBox<>();
		jButtonSignUp = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanelSignIn.setBackground(new java.awt.Color(35, 0, 106));

		jPanel2.setBackground(new java.awt.Color(22, 0, 68));

		jLabelSignIn.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 24)); // NOI18N
		jLabelSignIn.setForeground(new java.awt.Color(255, 255, 255));
		jLabelSignIn.setText("Sign In");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(130)
						.addComponent(jLabelSignIn, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(138)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(34)
						.addComponent(jLabelSignIn, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(34)));
		jPanel2.setLayout(jPanel2Layout);

		jLabel1.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 12)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("Usuario:");

		jTextFieldContrasena.setBackground(new java.awt.Color(255, 255, 255));
		jTextFieldContrasena.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 12)); // NOI18N
		jTextFieldContrasena.setForeground(new java.awt.Color(0, 0, 0));
		jTextFieldContrasena.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldContrasenaActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 12)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("Contraseña:");

		jTextFieldUsuario.setBackground(new java.awt.Color(255, 255, 255));
		jTextFieldUsuario.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 12)); // NOI18N
		jTextFieldUsuario.setForeground(new java.awt.Color(0, 0, 0));
		jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldUsuarioActionPerformed(evt);
			}
		});

		jButtonSignIn.setBackground(new java.awt.Color(22, 0, 68));
		jButtonSignIn.setForeground(new java.awt.Color(255, 255, 255));
		jButtonSignIn.setText("Sign In");
		jButtonSignIn.setToolTipText("");
		jButtonSignIn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonSignInActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanelSignInLayout = new javax.swing.GroupLayout(jPanelSignIn);
		jPanelSignInLayout.setHorizontalGroup(jPanelSignInLayout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanelSignInLayout.createSequentialGroup().addContainerGap()
						.addGroup(jPanelSignInLayout.createParallelGroup(Alignment.LEADING)
								.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
								.addGroup(jPanelSignInLayout.createSequentialGroup()
										.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGap(302))
								.addGroup(jPanelSignInLayout.createSequentialGroup()
										.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGap(280)))
						.addContainerGap())
				.addGroup(jPanelSignInLayout.createSequentialGroup().addGap(144)
						.addComponent(jButtonSignIn, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addGap(152))
				.addGroup(jPanelSignInLayout.createSequentialGroup().addGap(84)
						.addGroup(jPanelSignInLayout.createParallelGroup(Alignment.TRAILING)
								.addComponent(jTextFieldContrasena, GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
								.addComponent(jTextFieldUsuario, GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
						.addGap(60)));
		jPanelSignInLayout.setVerticalGroup(jPanelSignInLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanelSignInLayout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addGap(109).addComponent(jLabel1).addGap(35)
						.addComponent(jTextFieldUsuario, GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE).addGap(55)
						.addComponent(jLabel2).addGap(35)
						.addComponent(jTextFieldContrasena, GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE).addGap(80)
						.addComponent(jButtonSignIn, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addGap(48)));
		jPanelSignIn.setLayout(jPanelSignInLayout);

		jPanelSignUp.setBackground(new java.awt.Color(35, 0, 106));

		jPanel4.setBackground(new java.awt.Color(22, 0, 68));

		jLabelSignUp.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 24)); // NOI18N
		jLabelSignUp.setForeground(new java.awt.Color(255, 255, 255));
		jLabelSignUp.setText("Sign Up");
		jLabelSignUp.setMaximumSize(new java.awt.Dimension(89, 33));
		jLabelSignUp.setMinimumSize(new java.awt.Dimension(89, 33));

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel4Layout.createSequentialGroup().addGap(123)
						.addComponent(jLabelSignUp, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(109)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addGap(34)
						.addComponent(jLabelSignUp, GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE).addGap(34)));
		jPanel4.setLayout(jPanel4Layout);

		jLabel3.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 12)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("Nombre del cliente:");

		jTextFieldNombreContacto.setBackground(new java.awt.Color(255, 255, 255));
		jTextFieldNombreContacto.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 12)); // NOI18N
		jTextFieldNombreContacto.setForeground(new java.awt.Color(0, 0, 0));
		jTextFieldNombreContacto.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldNombreContactoActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 12)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setText("Nombre de contacto:");

		jTextFieldNombreCliente.setBackground(new java.awt.Color(255, 255, 255));
		jTextFieldNombreCliente.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 12)); // NOI18N
		jTextFieldNombreCliente.setForeground(new java.awt.Color(0, 0, 0));
		jTextFieldNombreCliente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldNombreClienteActionPerformed(evt);
			}
		});

		jLabel5.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 12)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setText("Telefono de contacto:");

		jTextFieldFax.setBackground(new java.awt.Color(255, 255, 255));
		jTextFieldFax.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 12)); // NOI18N
		jTextFieldFax.setForeground(new java.awt.Color(0, 0, 0));
		jTextFieldFax.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldFaxActionPerformed(evt);
			}
		});

		jLabel6.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 12)); // NOI18N
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6.setText("Fax:");

		jTextFieldTelefonoContacto.setBackground(new java.awt.Color(255, 255, 255));
		jTextFieldTelefonoContacto.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 12)); // NOI18N
		jTextFieldTelefonoContacto.setForeground(new java.awt.Color(0, 0, 0));
		jTextFieldTelefonoContacto.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldTelefonoContactoActionPerformed(evt);
			}
		});

		jRadioButtonCalle.setBackground(new java.awt.Color(35, 0, 106));
		jRadioButtonCalle.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 12)); // NOI18N
		jRadioButtonCalle.setForeground(new java.awt.Color(255, 255, 255));
		jRadioButtonCalle.setText("Calle");
		jRadioButtonCalle.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButtonCalleActionPerformed(evt);
			}
		});

		jRadioButtonAvenida.setBackground(new java.awt.Color(35, 0, 106));
		jRadioButtonAvenida.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 12)); // NOI18N
		jRadioButtonAvenida.setForeground(new java.awt.Color(255, 255, 255));
		jRadioButtonAvenida.setText("Avenida");
		jRadioButtonAvenida.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButtonAvenidaActionPerformed(evt);
			}
		});

		jRadioButtonBoulevard.setBackground(new java.awt.Color(35, 0, 106));
		jRadioButtonBoulevard.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 12)); // NOI18N
		jRadioButtonBoulevard.setForeground(new java.awt.Color(255, 255, 255));
		jRadioButtonBoulevard.setText("Boulevard");

		jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
		jComboBox1.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 12)); // NOI18N
		jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barcelona", "Boston", "Londres",
				"Madrid", "Paris", "San Francisco", "Sydney", "Talavera de la Reina", "Tokyo" }));

		jButtonSignUp.setBackground(new java.awt.Color(22, 0, 68));
		jButtonSignUp.setForeground(new java.awt.Color(255, 255, 255));
		jButtonSignUp.setText("Sign Up");
		jButtonSignUp.setToolTipText("");
		jButtonSignUp.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonSignUpActionPerformed(evt);
			}
		});

		jTextFieldDireccion = new JTextField();
		jTextFieldDireccion.setForeground(Color.BLACK);
		jTextFieldDireccion.setFont(new Font("Bitstream Vera Serif", Font.PLAIN, 12));
		jTextFieldDireccion.setBackground(Color.WHITE);

		javax.swing.GroupLayout jPanelSignUpLayout = new javax.swing.GroupLayout(jPanelSignUp);
		jPanelSignUpLayout.setHorizontalGroup(jPanelSignUpLayout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanelSignUpLayout.createSequentialGroup().addGroup(jPanelSignUpLayout
						.createParallelGroup(Alignment.TRAILING)
						.addGroup(jPanelSignUpLayout.createSequentialGroup().addContainerGap()
								.addGroup(jPanelSignUpLayout.createParallelGroup(Alignment.LEADING)
										.addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
										.addGroup(jPanelSignUpLayout.createSequentialGroup().addGroup(jPanelSignUpLayout
												.createParallelGroup(Alignment.LEADING)
												.addGroup(jPanelSignUpLayout.createSequentialGroup()
														.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, 141,
																Short.MAX_VALUE)
														.addGap(10))
												.addGroup(jPanelSignUpLayout.createSequentialGroup()
														.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, 148,
																Short.MAX_VALUE)
														.addGap(3))
												.addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
												.addGroup(jPanelSignUpLayout.createSequentialGroup()
														.addComponent(jLabel6, GroupLayout.DEFAULT_SIZE, 55,
																Short.MAX_VALUE)
														.addGap(96)))
												.addGap(196))))
						.addGroup(jPanelSignUpLayout.createSequentialGroup().addContainerGap()
								.addComponent(jRadioButtonCalle, GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
								.addGap(67)
								.addComponent(jRadioButtonAvenida, GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
								.addGap(49)
								.addComponent(jRadioButtonBoulevard, GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
						.addGroup(jPanelSignUpLayout.createSequentialGroup().addGap(59).addGroup(jPanelSignUpLayout
								.createParallelGroup(Alignment.TRAILING)
								.addComponent(jTextFieldNombreContacto, GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
								.addComponent(jTextFieldNombreCliente, GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
								.addComponent(jTextFieldTelefonoContacto, GroupLayout.DEFAULT_SIZE, 252,
										Short.MAX_VALUE)
								.addComponent(jTextFieldFax, GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
								.addGap(48)))
						.addContainerGap())
				.addGroup(jPanelSignUpLayout.createSequentialGroup().addGap(146)
						.addComponent(jButtonSignUp, GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE).addGap(116))
				.addGroup(Alignment.LEADING,
						jPanelSignUpLayout.createSequentialGroup().addGap(61)
								.addGroup(jPanelSignUpLayout.createParallelGroup(Alignment.LEADING)
										.addGroup(jPanelSignUpLayout.createSequentialGroup()
												.addComponent(jTextFieldDireccion, GroupLayout.DEFAULT_SIZE, 206,
														Short.MAX_VALUE)
												.addGap(58))
										.addGroup(jPanelSignUpLayout.createSequentialGroup()
												.addComponent(jComboBox1, 0, 252, Short.MAX_VALUE).addGap(58)))));
		jPanelSignUpLayout.setVerticalGroup(jPanelSignUpLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanelSignUpLayout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED).addComponent(jLabel3)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jTextFieldNombreCliente, GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE).addGap(18)
						.addComponent(jLabel4).addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jTextFieldNombreContacto, GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
						.addGap(18).addComponent(jLabel5).addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jTextFieldTelefonoContacto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addGap(26)
						.addGroup(jPanelSignUpLayout.createParallelGroup(Alignment.TRAILING, false)
								.addGroup(jPanelSignUpLayout.createSequentialGroup().addComponent(jLabel6).addGap(57))
								.addGroup(jPanelSignUpLayout.createSequentialGroup()
										.addComponent(jTextFieldFax, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addGap(35)))
						.addGroup(jPanelSignUpLayout
								.createParallelGroup(Alignment.BASELINE).addComponent(jRadioButtonCalle)
								.addComponent(jRadioButtonAvenida).addComponent(jRadioButtonBoulevard))
						.addPreferredGap(ComponentPlacement.UNRELATED)
						.addComponent(jTextFieldDireccion, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addGap(27)
						.addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addGap(18).addComponent(jButtonSignUp, GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
						.addGap(51)));
		jPanelSignUp.setLayout(jPanelSignUpLayout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(Alignment.TRAILING,
				layout.createSequentialGroup()
						.addComponent(jPanelSignIn, GroupLayout.PREFERRED_SIZE, 372, Short.MAX_VALUE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jPanelSignUp, GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(jPanelSignIn, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 576,
										Short.MAX_VALUE)
								.addComponent(jPanelSignUp, Alignment.LEADING, GroupLayout.DEFAULT_SIZE,
										GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap()));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jTextFieldContrasenaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldContrasenaActionPerformed
	}// GEN-LAST:event_jTextFieldContrasenaActionPerformed

	private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldUsuarioActionPerformed
	}// GEN-LAST:event_jTextFieldUsuarioActionPerformed

	private void jButtonSignInActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonSignInActionPerformed
		if (jTextFieldContrasena.getText().isEmpty() || jTextFieldUsuario.getText().isEmpty())
			JOptionPane.showMessageDialog(this, "No puede haber campos vacios.", "Error", JOptionPane.WARNING_MESSAGE);
		else {
			boolean existe = Cliente.existeCodClienteLogIn(Integer.parseInt(jTextFieldUsuario.getText().toString()));
			boolean contrasenaCorrecta = Cliente.comprobarContrasena(jTextFieldContrasena.getText().toString(),
					Integer.parseInt(jTextFieldUsuario.getText().toString()));

			if (existe == false)
				JOptionPane.showMessageDialog(this, "El usuario introducido no existe.", "Error",
						JOptionPane.WARNING_MESSAGE);
			else {
				if (contrasenaCorrecta == false)
					JOptionPane.showMessageDialog(this, "La contraseña no es correcta.", "Error",
							JOptionPane.ERROR_MESSAGE);
				else {
					// JOptionPane.showMessageDialog(this, "Login correcto.");
					BufferedImage myPicture;
					try {
						myPicture = ImageIO
								.read(new File("." + File.separator + "img" + File.separator + "Bienvenido.png"));
						JLabel picLabel = new JLabel(new ImageIcon(myPicture));
						JFrame frame = new JFrame();

						Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
						frame.add(picLabel);
						frame.setSize(pantalla.width / 2, pantalla.height / 2);
						frame.setLocationRelativeTo(null);
						frame.setVisible(true);
						jTextFieldUsuario.setText("");
						jTextFieldContrasena.setText("");
					} catch (IOException e) {
						System.err.println("\nERROR EN EL JLabel.");
						e.printStackTrace();
					}
				}
			}
		}
	}// GEN-LAST:event_jButtonSignInActionPerformed

	private void jTextFieldNombreContactoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldNombreContactoActionPerformed
	}// GEN-LAST:event_jTextFieldNombreContactoActionPerformed

	private void jTextFieldNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldNombreClienteActionPerformed
	}// GEN-LAST:event_jTextFieldNombreClienteActionPerformed

	private void jTextFieldFaxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldFaxActionPerformed
	}// GEN-LAST:event_jTextFieldFaxActionPerformed

	private void jTextFieldTelefonoContactoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldTelefonoContactoActionPerformed
	}// GEN-LAST:event_jTextFieldTelefonoContactoActionPerformed

	private void jRadioButtonCalleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButtonCalleActionPerformed
	}// GEN-LAST:event_jRadioButtonCalleActionPerformed

	private void jRadioButtonAvenidaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButtonAvenidaActionPerformed
	}// GEN-LAST:event_jRadioButtonAvenidaActionPerformed

	private void jButtonSignUpActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonSignUpActionPerformed
		if (jTextFieldNombreCliente.getText().isEmpty() || jTextFieldNombreContacto.getText().isEmpty()
				|| jTextFieldTelefonoContacto.getText().isEmpty() || jTextFieldFax.getText().isEmpty()) {
			JOptionPane.showMessageDialog(this, "No puede haber campos vacios.", "Error",
					JOptionPane.WARNING_MESSAGE);
		} else {
			boolean existe = Cliente.comprobarExisteCliente(jTextFieldNombreCliente.getText().toString());
			if (existe == true) {
				JOptionPane.showMessageDialog(this, "El usuario ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
				jTextFieldNombreCliente.setText("");
			} else {
				Cliente c;
				String direccion = "";
				if (jRadioButtonAvenida.isSelected()) {
					direccion = jRadioButtonAvenida.getText().toString() + " "
							+ jTextFieldDireccion.getText().toString();
				} else if (jRadioButtonBoulevard.isSelected()) {
					direccion = jRadioButtonBoulevard.getText().toString() + " "
							+ jTextFieldDireccion.getText().toString();
				} else if (jRadioButtonCalle.isSelected())
					direccion = jRadioButtonCalle.getText().toString() + " " + jTextFieldDireccion.getText().toString();
				c = new Cliente(jTextFieldNombreCliente.getText().toString(),
						jTextFieldNombreContacto.getText().toString(), jTextFieldTelefonoContacto.getText().toString(),
						jTextFieldFax.getText().toString(), direccion,
						(String) jComboBox1.getSelectedItem().toString());
				ClienteDAO.setConexion(ConexionDAO.getConexion());
				ClienteDAO.registrarCliente(c);
				JOptionPane.showMessageDialog(this, "Cliente registrado correctamente.");
				jTextFieldNombreCliente.setText("");
				jTextFieldNombreContacto.setText("");
				jTextFieldTelefonoContacto.setText("");
				jTextFieldFax.setText("");
			}
		}
	}// GEN-LAST:event_jButtonSignUpActionPerformed

	/**
	 * @param args the command line arguments
	 */
	/*
	 * public static void main(String args[]) { Set the Nimbus look and feel //
	 * <editor-fold defaultstate="collapsed" desc=" Look and feel setting code //
	 * (optional) ">
	 * 
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
	 * look and feel. For details see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 * 
	 * try { for (javax.swing.UIManager.LookAndFeelInfo info :
	 * javax.swing.UIManager.getInstalledLookAndFeels()) { if
	 * ("Nimbus".equals(info.getName())) {
	 * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } } } catch
	 * (ClassNotFoundException ex) {
	 * java.util.logging.Logger.getLogger(InterfazFormulario.class.getName()).log(
	 * java.util.logging.Level.SEVERE, null, ex); } catch (InstantiationException
	 * ex) {
	 * java.util.logging.Logger.getLogger(InterfazFormulario.class.getName()).log(
	 * java.util.logging.Level.SEVERE, null, ex); } catch (IllegalAccessException
	 * ex) {
	 * java.util.logging.Logger.getLogger(InterfazFormulario.class.getName()).log(
	 * java.util.logging.Level.SEVERE, null, ex); } catch
	 * (javax.swing.UnsupportedLookAndFeelException ex) {
	 * java.util.logging.Logger.getLogger(InterfazFormulario.class.getName()).log(
	 * java.util.logging.Level.SEVERE, null, ex); } // </editor-fold>
	 * 
	 * Create and display the form java.awt.EventQueue.invokeLater(new Runnable() {
	 * public void run() { InterfazFormulario fm = new InterfazFormulario();
	 * fm.setVisible(true); fm.setLocationRelativeTo(null); } }); }
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonSignIn;
	private javax.swing.JButton jButtonSignUp;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabelSignIn;
	private javax.swing.JLabel jLabelSignUp;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanelSignIn;
	private javax.swing.JPanel jPanelSignUp;
	// private javax.swing.JPanel jPanel1; // jPanel DE LA VentanaImagen.
	private javax.swing.JRadioButton jRadioButtonAvenida;
	private javax.swing.JRadioButton jRadioButtonBoulevard;
	private javax.swing.JRadioButton jRadioButtonCalle;
	private javax.swing.JTextField jTextFieldContrasena;
	private javax.swing.JTextField jTextFieldFax;
	private javax.swing.JTextField jTextFieldNombreCliente;
	private javax.swing.JTextField jTextFieldNombreContacto;
	private javax.swing.JTextField jTextFieldTelefonoContacto;
	private javax.swing.JTextField jTextFieldUsuario;
	private javax.swing.JTextField jTextFieldDireccion;
}
