package listas.enlazada;

public class ListaEnlazada {

	/**
	 * LA LISTA, AL CONTRARIO QUE LOS ARRAYS, PERMITE MODIFICAR SU CAPACIDAD,
	 * MANEJANDO LOS DATOS DE FORMA DINAMICA.
	 * 
	 * LAS FUNCIONES BASICAS DE UNA LISTA ENLAZADA SON:
	 * - INSERTAR: AL PRINCIPIO O AL FINAL DE LA LISTA,
	 * O BIEN EN ORDEN.
	 * - ELIMINAR: ELIMINANDO UN NODO DE LA LISTA, MEIDANTE SU POSICION O
	 * POR EL DATO.
	 * - BUSCAR: QUE BUSCA UN ELEMENTO EN LA LISTA.
	 */
	private Nodo primero; // PUNTERO AL PRIMER NODO.
	private long largo; // CANTIDAD DE ELEMENTOS EN LA LISTA.

	public void insertarAlPrincipio(Object dato) {
		Nodo puntero = primero; // CREO UN PUNTERO QUE APUNTA AL PRINCIPIO DE LA LISTA.
		
	}
}